// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Comforter } from "next/font/google";
const inter = Comforter({ subsets: ["latin"],display: "swap",weight:'400' });//swap 加载字体前使用默认字体


export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} pt-20 min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 text-white`}>

        <main>{children}</main>
      </body>
    </html>
  );
}